sonar.projectKey=jm-strat_sdet-cicd-training-demo
sonar.organization=jm-strat

# TODO (Module 5): Replace YOUR_PROJECT_KEY and YOUR_SONAR_ORG
# with values from your SonarCloud account after connecting your repo.
# Get these from: https://sonarcloud.io → your project → Information tab

sonar.sources=playwright-typescript
sonar.exclusions=**/node_modules/**,**/playwright-report/**

sonar.tests=playwright-typescript/tests
sonar.test.inclusions=**/*.spec.ts
